### ISSUE TITLE
big problem . not show data

### ISSUE THREAD

**Issue by Q8HMA-zz** [xombiemp/rutorrentMobile#16] opened 2016-03-31 20:54 UTC
Hello 

The problem is all the data not show

my seedbox is big have over 3K torrent for 12 tracker

i cant see any things only white background no data not torrents file no tracker url any things

can some one help me with it ??

thnx

**Comment by Jeci** [comment] 2016-06-29 08:31
I'm having the same issue, just seeing a blank screen. 

I also have quite a few torrents loaded (700+).

**Comment by hit** [comment] 2016-11-30 18:05
Torrents are displayed, but only with a massive delay depending on the amount of torrents (=too long loading time).

**Comment by xombiemp** [comment] 2017-06-01 01:16
Try the latest.  This commit might have helped https://github.com/xombiemp/rutorrentMobile/commit/12a4a2b2036ae0a24fe4cd8a6778e673b2ead931

**Comment by Whisper40** [comment] 2017-10-19 05:13
@xombiemp Hello, the problem is the same for me on rutorrent 3.8 :  http://prntscr.com/gz805h

**Comment by milesbenson** [comment] 2018-01-07 11:38
Same issue here, around 300 torrents in the list, mobile plugin does not show any of my torrents.

**Comment by bsattar123** [comment] 2018-05-02 17:04
Hey, did you guys manage to get this fixed somehow. Same problem here, UI is fine but no torrents showing up. Cheers

**Comment by shimi269** [comment] 2019-03-13 23:59
Did anyone find a fix for this issue? Mine is also showing as blank, tried all the fixes suggested and nothing.

**Comment by Machado117** [comment] 2019-04-22 20:49
I had the same issue. Fixed it by enabling the httprpc plugin that I had previously disabled.

**Comment by PeggyFree** [comment] 2019-04-25 08:05
Hello, I have the same problem. I have multiple users. When I load the mobile version, I get no content and this error in the console : 

"Failed to load resource: the server responded with a status of 502 (Bad Gateway)".

The console shows that the url linked to this error is http://my_torrent_server/my_username

I think the right url should be http://my_torrent_server/**rutorrent/**my_username

**Comment by PeggyFree** [comment] 2019-04-29 16:37
I check the dev tools, the page retrieves the content of the page in xml file. I don't know why several "http://my_torrent_server/my_username" are correctly executed, and why one of them fails. I tried to understand the underlying request but could'nt understand it's content. Here it is : 

POST http://XXX.XXX.XXX.XXX/USER1 HTTP/1.1
Host: XXX.XXX.XXX.XXX
Proxy-Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
Authorization: Basic BLAHBLAHBLAH
Accept: application/xml, text/xml, */*; q=0.01
Origin: http://XXX.XXX.XXX.XXX
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
DNT: 1
Content-Type: text/xml; charset=UTF-8
Referer: http://XXX.XXX.XXX.XXX/rutorrent/?mobile=1
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7


I can't find any payload in this request.  Here is the answer : 

HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Mon, 29 Apr 2019 16:31:44 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 537
Connection: keep-alive
ETag: "5c0692e1-219"

I could'nt find the reason in the log.

**Comment by Micdu70** [comment] 2019-04-29 17:15
@PeggyFree Hello, please use / enable "httprpc" plugin to have a better and faster communication with rtorrent. No need to configure a SCGI remote url ("/USER1") on your webserver (but you can keep it ofc.). ;)

**Comment by 07416** [comment] 2019-07-24 17:44
> 
> 
> @PeggyFree Hello, please use / enable "httprpc" plugin to have a better and faster communication with rtorrent. So, no need to keep a SCGI remote url ("/USER1") configuration on your webserver. ;)

How do I enable the `httprpc` plugin?

**Comment by 07416** [comment] 2019-07-24 18:00
> 
> 
> please use / enable "httprpc" plugin to have a better and faster communication with rtorrent. So, no need to keep a SCGI remote url ("/USER1") configuration on your webserver. ;)

further information: https://github.com/Novik/ruTorrent/issues/1405#issuecomment-278085638

**Comment by 07416** [comment] 2019-07-25 06:11
@Micdu70 May I ask for instructions? If I add `network.scgi.open_port = 127.0.0.1:5000` to `.rtorrent.rc` rTorrent runs, but ruTorrent doesn't. Do I have to edit ruTorrent's `config.php`?

**Comment by xombiemp** [comment] 2023-12-06 06:40
Added requirement to use the httprpc plugin in the readme.

**Closed by xombiemp** 2023-12-06 06:40 UTC
